### ISSUE TITLE
Install Snakemake

### ISSUE THREAD

**Issue by gwcde** [WatsonLab/KOunt#3]
Hello
It's interesting to obtain KO abundance through metagenomic analysis, so I tried to run your code. However, I encountered some issues during the installation process.The error message "version problem" occurred when I tried to install Snakemake following the above steps.

The following packages are incompatible
└─ snakemake   is installable with the potential options
   ├─ snakemake [3.10.0|3.10.1|...|3.9.1] would require
   │  └─ python 3.4* , which does not exist (perhaps a missing channel);
   ├─ snakemake [3.10.0|3.10.1|...|3.9.1] would require
   │  └─ python 3.5* , which can be installed;
   ├─ snakemake [3.11.2|3.12.0|3.13.0|3.13.2|3.13.3] would require
   │  └─ python 3.6* , which can be installed;
   ├─ snakemake 4.0.0 would require
   │  └─ aioeasywebdav  , which does not exist (perhaps a missing channel);
   ├─ snakemake [4.1.0|4.2.0|...|5.3.0] would require
   │  └─ ratelimiter  , which does not exist (perhaps a missing channel);
   └─ snakemake [5.10.0|5.11.0|...|7.9.0] would require
      └─ python-irodsclient  , which does not exist (perhaps a missing channel).

best and thanks
gu wen chao

**Comment by jmattock5** [comment]
Hi gu wen chao,

This looks like a python issue, what versions of python and conda are you using? If not recent I'd recommend updating both.

Thanks,
Jenny

**Comment by gwcde** [comment]
thanks for your reply
I tried to specify python=3.6 when installing the conda environment,so the Snakemake can be installed successfully. 
However, I don't know if there is any problem with configuring the environment this way, since the version is not the latest. If possible, could you share your environment.
best and thanks
gu wen chao

**Comment by jmattock5** [comment]
You should be able to find my snakemake env in `envs/snakemake_mamba.yaml`. You can try recreating it with `conda env create -n snakemake_mamba -f envs/snakemake_mamba.yaml`.
Thanks,
Jenny

**Comment by gwcde** [comment]
Hi Jenny
When I run the following command: snakemake -k --ri --use-conda --cores 8, i encountered the following error message:

rule trim:
    input: test_fastqs/ERR2027889_005/ERR2027889_005_R1.fastq.gz, test_fastqs/ERR2027889_005/ERR2027889_005_R2.fastq.gz
    output: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp
Activating conda environment: .snakemake/conda/af96229be3e11fc786ca0433f7154346_
/bin/bash: line 3: fastp: command not found
/bin/bash: line 8: fastq_info: command not found
read names not unique or fastqs invalid
Waiting at most 5 seconds for missing files.
MissingOutpuut: out/Touch/trim_ERR2027889_005
    jobid: 1
    reason: Missing output files: out/Touch/trim_ERR2027889_005
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp
Activating conda environment: .snakemake/conda/af96229be3e11fc786ca0433f7154346_
/bin/bash: line 3: fastp: command not found
/bin/bash: line 8: fastq_info: command not found
read names not unique or fastqs invalid
Waiting at most 5 seconds for missing files.
MissingOutputException in rule trim in file /hdd/metagenome/KOunt/Snakefile, line 139:
Job 1  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
out/Touch/trim_ERR2027889_005

It seems to be a path issue. When I set this path "out/Touch/trim_ERR2027889_005", I encountered a new error:

rule megahit:
    input: out/Touch/trim_ERR2027889_005
    output: out/assemblies/ERR2027889_005/ERR2027889_005.contigs.fa
    jobid: 2
    reason: Missing output files: out/assemblies/ERR2027889_005/ERR2027889_005.contigs.fa
    wildcards: id=ERR2027889_005
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/ad0752a02fde5c39a579ce088620b5ad_
/bin/bash: line 2: megahit: command not found
mv: cannot stat 'out/megahit/ERR2027889_005/final.contigs.fa': No such file or directory
/bin/bash: line 4: ./scripts/add_sample_name.sh: Permission denied
rm: cannot remove 'out/megahit/ERR2027889_005/': No such file or directory
[Thu May 11 11:40:58 2023]
Error in rule megahit:
    jobid: 2
    input: out/Touch/trim_ERR2027889_005
    output: out/assemblies/ERR2027889_005/ERR2027889_005.contigs.fa
    conda-env: /hdd/metagenome/KOunt/.snakemake/conda/ad0752a02fde5c39a579ce088620b5ad_
    shell:

    mkdir -p out/megahit
    megahit -m 4.8e+10 --kmin-1pass --k-list 27,37,47,57,67,77,87 --min-contig-len 300 -t 1 -1 out/trimmed/ERR2027889_005/ERR2027889_005.trimmed.R1.fastq.gz -2 out/trimmed/ERR2027889_005/ERR2027889_005.trimmed.R2.fastq.gz -o out/megahit/ERR2027889_005/
    mv out/megahit/ERR2027889_005/final.contigs.fa out/assemblies/ERR2027889_005/ERR2027889_005.contigs.fa
    ./scripts/add_sample_name.sh out/assemblies/ERR2027889_005/ERR2027889_005.contigs.fa ERR2027889_005
    rm -r out/megahit/ERR2027889_005/

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)tException in rule trim in file /hdd/metagenome/KOunt/Snakefile, line 139:
Job 1  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
out/Touch/trim_ERR2027889_005

best and thanks
gu wen chao

**Comment by jmattock5** [comment]
Hi gu wen chao,
This looks to me like an issue with env installation. These error messages 
`/bin/bash: line 3: fastp: command not found`
`/bin/bash: line 8: fastq_info: command not found`
`/bin/bash: line 2: megahit: command not found`
suggest that Snakemake can't use the fastp and megahit conda envs which would explain the missing files. Could you try and remove the hidden Snakemake folder with `rm -r .snakemake/` and then try `snakemake -k --ri --use-conda --cores 8` again. It should begin by installing the conda envs again which should hopefully sort your problem.

Thanks,
Jenny

**Comment by jmattock5** [comment]
I'm going to close this issue, please make another if you have any more questions.
