### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by LorrieMacc** [WatsonLab/KOunt#5]
Hi Jennifer,

Thank you very much for creating this new tool :)
I have just installed KOunt following the instructions but ran into a problem while running the test run.

I think the issue is at step 6 : 
Missing output files: out/Abundance_Outputs/ERR2027889_005/ERR2027889_005_coverage; Input files updated by another job: out/Prodigal_Outputs/filtered_gffs/ERR2027889_005/ERR2027889_005.gff, scripts/BamDeal-0.24/bin/BamDeal_Linux, out/Abundance/ERR2027889_005/ERR2027889_005_bwa

Could you please help me to solve this problem ?
I am also attaching the log and err
[KOunt_Install_err.txt](https://github.com/WatsonLab/KOunt/files/12378183/KOunt_Install_err.txt)
[KOunt_Install_log.txt](https://github.com/WatsonLab/KOunt/files/12378184/KOunt_Install_log.txt)

Thank you very much in advance
lorrie

**Comment by jmattock5** [comment]
Hi Lorrie,

Thanks for your feedback! From your log files it looks like the issue is that the scripts haven't been made executable. Please can you try the following and let me know if you still have issues?
`chmod +x scripts/*sh`

Thanks,
Jenny
